name 'themis-finals-service1-checker'
description 'Installs and configures Themis Finals sample service1 checker'
version '1.4.0'

recipe 'themis-finals-service1-checker', 'Installs and configures Themis Finals sample service1 checker'
depends 'git', '~> 8.0.0'
depends 'git2', '~> 1.0.0'
depends 'rbenv', '1.7.1'
depends 'supervisor', '~> 0.4.12'
depends 'chef_nginx', '~> 6.1.1'
depends 'ssh-private-keys', '~> 2.0.0'
depends 'ssh_known_hosts', '~> 4.0.0'
depends 'themis-finals-utils', '~> 1.0.0'
depends 'instance', '~> 1.0.0'
